### ISSUE TITLE
[WISH] Headerlayout

### ISSUE THREAD

**Issue by MarcusBi** [2Abendsegler/GC_little_helper_2AS#1]
Sehr schön, dass der Header wieder richtig funktioniert und alles angezeigt wird. Allerdings fände ich es noch perfekter, wenn das Menü wieder linksbüding und das Messagecenter etc. rechtsbündig zur eingestellten Seite angezeigt wird (am besten per Auswahl in der Konfiguration). Bei einem großen Monitor (>1600px) sieht es doch recht merkwürdig aus bzw. ist von der Bedinung her wirklich gewöhnungsbedürftig, das Menü ganz links am Seitenrand zu haben...

**Comment by 2Abendsegler** [comment]
Hi, 

im GClh Config gibt es die Möglichkeit das Menü rechts auszurichten. 
Schau mal [hier](https://www.geocaching.com/my/#GClhShowConfig#gclh_linklist). Wähle dort "Linklist / Navigation show" und aktiviere gegebenenfalls "Show Linklist at menu as drop-down list". Wähle dann "**Arrange the menu right**". 
Das müßte dann genau das sein, was im GClh Original vorhanden ist.
Was meinst Du? 

LG Frank
PS: Vielleicht können wir uns besser im Forum austauschen.

**Comment by MarcusBi** [comment]
Hallo Frank,

das, was du beschrieben hast, trifft die Sache nicht ganz. Ich habe dir mal
zwei Bilder angehängt, dann verstehst du, was ich meinte...

LG, Marcus
PS: Respekt für die Arbeit, die du da geleistet hast!

Am 24. November 2016 um 18:08 schrieb 2Abendsegler <notifications@github.com

**Comment by 2Abendsegler** [comment]
Ich weiß warum ich schrieb, dass wir uns vielleicht besser im Forum austauschen könnten. :)
Ich kann die Bilder hier nicht finden.

**Comment by MarcusBi** [comment]
Upps...mein Fehler. Ich hatte sie an die Mail gehängt, welche Github automazisch hier einträgt (aber eben ohne Anhänge). Hier also die Bilder...
![ist-zustand](https://cloud.githubusercontent.com/assets/23725271/20616528/2c86219e-b2e3-11e6-8921-b7d19e641b91.jpg)
![soll-zustand](https://cloud.githubusercontent.com/assets/23725271/20616529/2cd7b7e8-b2e3-11e6-8dae-029efbd15f45.jpg)

PS: Ich finde einen direkten Austausch hier besser (Forum = Anwender, Gihub = Entwickler). Und wo passt es besser alser unter Issues bei Github ;-) ?

**Comment by 2Abendsegler** [comment]
Ok, verstehe.
Ich hatte Dich so verstanden, dass das bereits eine Funktionalität des Original GClh war. Das ist aber nicht so, oder? Hier wäre dann nämlich etwas an mir vorbeigegangen, so etwas kommt ja schon mal vor, ist also nicht ausgeschlossen. Dann würde ich nur gerne wissen, welche Einstellungen dazu führen?

Zum hiesigen Austausch:
Mein User, zu diesem Thema, auf hiesiger Plattform wird mit einiger Wahrscheinlichkeit nicht lange bestehen, dieses Repository erst recht nicht. Wie ich schon im Forum versucht habe zu verdeutlichen, ist der GClh nicht mein Kind. Ich bin derzeit nur die Nanny. Wenn ich ausreichend Approvals für diese Testversion erhalte, werde ich den Erfinder des GClh bitten, diese Version zu übernehmen. Und schon ist hier Feierabend. :) Im Forum werden die Dinge weiter zur Verfügung stehen, wenn auch in dem ewig langen Thread ziemlich unübersichtlich. Wenn Du also möchtest, dass Deine Beiträge in absehbarer Zeit in den ewigen Weiten des Internet Universums unauffindbar verschwinden, dann bestehen hier nicht gerade schlechte Aussichten, dies zu erreichen. ;)

**Comment by MarcusBi** [comment]
Da hast du natürlich auch wiederum recht. Wie dem auch sei, es wäre echt klasse, wenn du mirt Torsten eine Basis für eine offizielle neue Version finden könntest. Ich hab auch schon mal selber Hand angelegt, habe aber im Grunde genommen nicht so wirklich die Ahnung, was ich da eigentlich treibe. Wenn das jetzt C, C# oder C++-Code wäre...aber Script? Nee - nicht mein Ding. Aber egal...

Nochmal (letztmalig hier) zur eigentlichen Sache : Selbst OHNE gclh wird das Menü eher zentriert dargestellt. Zwar nicht unbedingt bündig mit dem Rand der dargestellten Seitenbreite, aber eben eher mittig dort, wo auch der Inhalt der Seite zu finden ist. Wäre echt klasse, wenn du etwas in der Art hin bekommen würdest. Also Quasi einfach das Menü aus der Original-Darstellung "nach oben" in den grünen Bereich schieben.

![geocaching _ your profile - mozilla firefox 2016-11-25 14 52 45](https://cloud.githubusercontent.com/assets/23725271/20627675/d415ed70-b321-11e6-808c-17305c91e584.jpg)

VG, Marcus

**Comment by 2Abendsegler** [comment]
Ja ok ... , ich nehme es auf die Wunschliste. Du stehst auch nicht alleine mit Deinem Wunsch. :)
LG Frank

**Comment by 2Abendsegler** [comment]
Sorry, hier ist irgendetwas schiefgelaufen. Und es steht auch etwas schief. Beim fix #1 erscheint [WISH] Headerlayout. und dann die Beschreibung "MapQuest maps are no longer available" vom Pull Request.
Naja, egal. Der Wunsch ist nun wieder offen.

**Comment by 2Abendsegler** [comment]
Ist in der Wunschliste enthalten.
[Wunschliste Nr. 10 ](https://rawgit.com/2Abendsegler/GC_little_helper_2AS/master/GClh%20Wünsche.pdf)
