### ISSUE TITLE
[BUG] Link to configuration dialog not available

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GC_little_helper_2AS#2]
The link to the configuration dialog on side "My Profile" is no longer available.

The **element ctl00_ContentBody_WidgetMiniProfile1_logOutLink** was removed. You can use element **ctl00_ContentBody_WidgetMiniProfile1_memberProfileLink**.

CachingFoX

Version: 11.6.4

**Comment by 2Abendsegler** [comment]
Fixed with version 11.6.5.
Thanks
