### ISSUE TITLE
[BUG] Map layer hill shadow doesn't work

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GC_little_helper_2AS#3]
The hill shadow layer in geocaching map doesn't work anymore.

Script Version: 11.6.4
Reason
The tiles moved from toolserver.org to wmflabls.org
new http://{s}.tiles.wmflabs.org/hillshading/{z}/{x}/{y}.png
old: http://toolserver.org/~cmarqu/hill/{z}/{x}/{y}.png

**Comment by 2Abendsegler** [comment]
Fixed with version 11.6.5.
Thanks
