### ISSUE TITLE
[BUG] Fehlender Logeintrag in Cache Listings

### ISSUE THREAD

**Issue by DieBatzen** [2Abendsegler/GC_little_helper_2AS#4]
Hallo Frank,

manchmal wird der zeitlich erste Logeintrag bei einem Cachelisting nicht angezeigt, sonst sind aber alle Logs sichtbar.
Beispielsweise aktuell bei dem hier: https://coord.info/GC6WF8P

Die Einstellung 
_Show xx logs (0 = all)_ 
scheint dieses Verhalten zu beeinflussen.
Nehme ich das Häkchen raus oder setze die Option auf 6 (oder weniger) Logs, dann fehlt bei obigem Listing der Publishlog.
Setze ich hingegen die Option auf 7 (oder mehr) Logs, dann wird der Publishlog angezeigt.
Aktuell sind insgesamt 6 Logeinträge vorhanden.

Nur eine Kleinigkeit, dennoch erwähnenswert.

Gruß,
Thomas

PS: Alle Daumen, die ich habe, hoch - super Arbeit! Wir haben deine Version ausgiebig getestet und sind begeistert. Ganz klares **approved für Übernahme in GClh**!

Edit: hier noch die Systemdaten
Windows 10, Greasemonkey 3.9, FF ESR 45.5.0, Sprache bei GS: Englisch, GC little helper (2As): 11.6.5

**Comment by 2Abendsegler** [comment]
Ich hatte mich schon einige an diesem Problem versucht, kam aber nicht weiter. Das Beispiel war nun super, warum nicht mal im Kleinen versuchen. 
Vielen Dank.

Mit Version 11.6.6 behoben.
